# Generated by Django 4.2.7 on 2026-08-29 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_cropsession_remove_growthprediction_predicted_yield_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='cropsession',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='plantimage',
            name='slot',
        ),
        migrations.AddField(
            model_name='cropsession',
            name='crop_variety',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cropsession',
            name='farmer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cropsession',
            name='field_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cropsession',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cropsession',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cropsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='plantimage',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_readings', to='agriculture.cropsession'),
        ),
        migrations.AlterField(
            model_name='cropsession',
            name='crop_name',
            field=models.CharField(default='Green Gram', max_length=100),
        ),
        migrations.AlterField(
            model_name='plantimage',
            name='disease_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='CropNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('observation', 'Observation'), ('action', 'Action Taken'), ('alert', 'Alert'), ('milestone', 'Milestone')], default='observation', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriculture.plantimage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_notes', to='agriculture.cropsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
