# Generated by Django 4.2.30 on 2026-09-04 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0003_alter_cropsession_options_and_more'),
        ('agriculture', '0003_leaf_area_fields'),
    ]

    operations = [
    ]
